"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Copy, Check, Download, Code2, FileText } from "lucide-react";
import { useWorkflowStore } from "@/stores/workflow-store";

export function CodeViewer() {
  const [copied, setCopied] = useState(false);
  const { workflows, selectedWorkflowId } = useWorkflowStore();
  const selected = workflows.find((w) => w.id === selectedWorkflowId) ?? workflows.find((w) => w.status === "RUNNING");

  const analystCode = (selected?.analystOutput?.code as string | undefined) ?? "";
  const analystFindings = (selected?.analystOutput?.findings as string | undefined) ?? "";
  const schedulerPlan = (selected?.schedulerOutput?.recommended_schedule as string | undefined) ?? "";
  const verdict = (selected?.librarianVerdict?.verdict as string | undefined) ?? "";
  const confidence = (selected?.librarianVerdict?.confidence_score as number | undefined) ?? undefined;

  const summaryText =
    [
      selected?.goalTitle ? `Goal: ${selected.goalTitle}` : "",
      verdict ? `Verdict: ${verdict}${typeof confidence === "number" ? ` (confidence: ${confidence.toFixed(2)})` : ""}` : "",
      schedulerPlan ? `\nRecommended schedule:\n${schedulerPlan}` : "",
      analystFindings ? `\nFindings:\n${analystFindings}` : "",
    ]
      .filter(Boolean)
      .join("\n");

  const handleExport = () => {
    const content = analystCode.trim() ? analystCode : summaryText.trim();
    if (!content) return;
    const filename = showingCode ? "analysis.py" : "result.txt";
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = async () => {
    const toCopy = analystCode.trim() ? analystCode : summaryText.trim();
    if (!toCopy) return;
    await navigator.clipboard.writeText(toCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const lines = (analystCode.trim() ? analystCode : summaryText || "# No output yet — start a workflow on the left.").split("\n");
  const showingCode = analystCode.trim().length > 0;

  return (
    <div className="glass flex flex-col h-full overflow-hidden">
      {/* Header */}
      <div
        className="flex items-center justify-between px-4 py-2.5 border-b shrink-0"
        style={{ borderColor: "var(--border)" }}
      >
        <div className="flex items-center gap-2">
          {showingCode ? <Code2 size={14} style={{ color: "var(--muted)" }} /> : <FileText size={14} style={{ color: "var(--muted)" }} />}
          <span className="text-xs font-mono font-medium" style={{ color: "var(--text-dim)" }}>
            {showingCode ? "analysis.py" : "result.txt"}
          </span>
          <span
            className="text-[10px] px-1.5 py-0.5 rounded-badge"
            style={{ background: "var(--success-dim)", color: "var(--success)", border: "1px solid rgba(34,197,94,0.25)" }}
          >
            {showingCode ? "Generated by Analyst" : "Workflow output"}
          </span>
        </div>
        <div className="flex items-center gap-1">
          <motion.button
            whileTap={{ scale: 0.95 }}
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-2.5 py-1 rounded-md text-xs transition-colors hover:bg-[var(--surface-2)]"
            style={{ color: copied ? "var(--success)" : "var(--text-dim)" }}
          >
            {copied ? <Check size={13} /> : <Copy size={13} />}
            {copied ? "Copied!" : "Copy"}
          </motion.button>
          <button
            onClick={handleExport}
            className="flex items-center gap-1.5 px-2.5 py-1 rounded-md text-xs transition-colors hover:bg-[var(--surface-2)]"
            style={{ color: "var(--text-dim)" }}
          >
            <Download size={13} />
            Export
          </button>
        </div>
      </div>

      {/* Code */}
      <div className="flex-1 overflow-auto">
        <div className="code-block h-full rounded-none border-0">
          <table className="w-full border-collapse text-xs font-mono">
            <tbody>
              {lines.map((line, idx) => (
                <tr key={idx} className="hover:bg-white/[0.03] group">
                  <td
                    className="select-none pr-4 pl-4 py-0.5 text-right w-8 border-r"
                    style={{
                      color: "var(--text-faint)",
                      borderColor: "var(--border)",
                      userSelect: "none",
                    }}
                  >
                    {idx + 1}
                  </td>
                  <td className="pl-4 pr-4 py-0.5 whitespace-pre" style={{ color: "#a8b4c6" }}>
                    {showingCode ? colorizeSimple(line) : line}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

function colorizeSimple(line: string): React.ReactNode {
  if (line.trimStart().startsWith("#")) {
    return <span style={{ color: "#6a7a8a", fontStyle: "italic" }}>{line}</span>;
  }
  if (line.startsWith("import ") || line.startsWith("from ")) {
    return <span style={{ color: "#7dd3fc" }}>{line}</span>;
  }
  if (line.trimStart().startsWith("def ") || line.trimStart().startsWith("class ")) {
    return <span style={{ color: "#c084fc" }}>{line}</span>;
  }
  if (line.includes("print(")) {
    return <span style={{ color: "#86efac" }}>{line}</span>;
  }
  return line;
}
